### ISSUE TITLE
test the installation instructions for running locally

### ISSUE THREAD

**Issue by edbedbe** [formal-web/python-documentor#1]
I have only used the installation instructions myself and I wrote them, so I don't know if they work for other people and communicate the process well. 

We should review the installation instructions in `README.md` and make any changes to make them more clear or approachable.

**Comment by emanuelbierman** [comment]
Can confirm the installation process works as described in the '''README.md'''.

**Comment by edbedbe** [comment]
Glad it worked. :) Good catch about installing `pip`. I think I'll add a link to [Python's requirements for installing packages](https://packaging.python.org/tutorials/installing-packages/#requirements-for-installing-packages) to that section. Thanks!
